### ISSUE TITLE
buildfile command

### ISSUE THREAD

**Issue by tonistiigi** [tonistiigi/buildx#13]
Add another command that produces a higher level build operation based on config from a file. An input file can be compose or another format that can stack the cli options into separate targets.

On invoking command all builds are invoked concurrently, looking like a single build to the user.

`buildx buildfile -f compose.yml [target] [target]..`

The file allows stacking all cli options, including things like exporter and remote cache settings (but probably excluding entitlements). When using multiple files you can override some properties with a file that is not committed to git. The cli flags can be used for the highest priority override. The non-compose format can support sharing code so that groups of options can be used as part of multiple targets.

The name needs improvement.

**Comment by AkihiroSuda** [comment]
s/buildfile/compose/ ?

**Comment by tonistiigi** [comment]
I don't think compose is ideal format for this, because of the missing code reuse and missing configuration options. Just compose is somewhat similar and widespread so makes sense to support it as well.

**Comment by tonistiigi** [comment]
#16
