### ISSUE TITLE
`buildx use default` doesn't switch to local

### ISSUE THREAD

**Issue by tiborvass** [tonistiigi/buildx#30]
When a remote node is added, one expects `buildx use default` to switch back to local, but `buildx ls` still shows the remote builder as current.

**Comment by tonistiigi** [comment]
currently when switching to a docker context with `buildx use` we will show https://github.com/tonistiigi/buildx/blob/master/commands/use.go#L42 . I wonder if we should show same in this case and leave current behavior of `buildx use default` only to the case where `currentcontext==default`
