### ISSUE TITLE
ls output is weird

### ISSUE THREAD

**Issue by AkihiroSuda** [tonistiigi/buildx#36]
```
$ docker buildx ls
NAME/NODE DRIVER/ENDPOINT STATUS  PLATFORMS
default * docker
  default default         running linux/amd64
```

**Comment by tonistiigi** [comment]
The output is expected, but yes it is not very obvious, especially when you only have the default config visible. This view shows both builders and the nodes that they are using. There is one builder instance "default" and that has one node "default" under it.

Open to suggestions on how to improve it but it needs to maintain its functionality when there are more instances and instances with multiple nodes.
